micronaut:
  application:
    name: messaging-rabbitmq
  executors:
    consumer:
      type: FIXED

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: 5672
  username: rabbit
  password: rabbit

kafka:
  bootstrap:
    servers: ${KAFKA_SERVER:localhost}:9092

micro:
  rabbit:
    queue-in: micronaut-queue
  kafka:
    topic-in: kafka-car